### ISSUE TITLE
Error with bracket

### ISSUE THREAD

**Issue by norwayRP** [bluupie/qb-taxing#1]
Hi

Keep getting this error now and then.

`SCRIPT ERROR: @qb-taxing/server/main.lua:37: attempt to concatenate a nil value (local 'bracket')`

Any idea what it could be?

**Comment by bluupie** [comment]
Did you change the bracket name by any chance ?

**Comment by bluupie** [comment]
try the latest update

**Comment by norwayRP** [comment]
Keep getting this now

[    script:qb-taxing] SCRIPT ERROR: @qb-taxing/server/main.lua:41: attempt to concatenate a table value (local 'bracket')
